// ===============================================
// Autogenerated config file
// Use this to configure your workers environment
// ===============================================

export default {
    extControllers: [], // Controllers in ../src will be discovered automatically
    prehandlers: [],
    posthandlers: [],
    kvBindings: {},
}
 